// Actions
export const OUVRE_LE_PANIER = 'OUVRE_LE_PANIER';
export const FERME_LE_PANIER = 'FERME_LE_PANIER';
export const AJOUTE_UN_ARTICLE_DANS_LE_PANIER = 'AJOUTE_UN_ARTICLE_DANS_LE_PANIER';
export const RETIRE_UN_ARTICLE_DU_PANIER = 'RETIRE_UN_ARTICLE_DU_PANIER';
export const CHANGE_LA_QUANTITE_D_UN_ARTICLE = 'CHANGE_LA_QUANTITE_D_UN_ARTICLE';
export const VIDE_LE_PANIER = 'VIDE_LE_PANIER';
export const CALCULE_LE_TOTAL_DU_PANIER = 'CALCULE_LE_TOTAL_DU_PANIER';
export const OUVRE_LA_BABYBOX = 'OUVRE_LA_BABYBOX';
export const FERME_LA_BABYBOX = 'FERME_LA_BABYBOX';